version: '3.8'

services:
  osint-api:
    build: .
    ports:
      - "8080:8080"
      - "9229:9229"
    env_file:
      - .env
    depends_on:
      - redis
      - mongo
    networks:
      - backend_net
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  redis:
    image: redis:latest
    container_name: osint_redis
    ports:
      - "6379:6379"
    networks:
      - backend_net
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:latest
    container_name: osint_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

volumes:
  redis-data:
  mongo-data:

networks:
  backend_net:
    external: true